In [1]:
import numpy as np
from os.path import join
import pickle
exp_type = 'sc-k'
num_src = 'nums1-3'

emb_types = ['word2vec-wiki', 'word2vec-giga', 'glove-wiki', 'glove-giga', 'fasttext-wiki', 'fasttext-giga','random']

In [10]:
n_repeat = 5
res = np.zeros((n_repeat,len(emb_types),2))
for i in range(1,n_repeat+1):
    for j,emb_type in enumerate(emb_types):
        res_name =  '_'.join(['res-acc',num_src, exp_type, emb_type])
        res[i-1][j,:] = np.load(join('data',str(i),res_name+'.npy'))

In [8]:
n_repeat = 5
res = np.zeros((n_repeat,len(emb_types),2))
for i in range(1,n_repeat+1):
    for j,emb_type in enumerate(emb_types):
        f_name = '_'.join(['res-exp',num_src, exp_type, emb_type])+'.pkl'
        with open(join('data',str(i),f_name),'rb') as f:
            acc = pickle.load(f)
            res[i-1][j,0] = acc['orig_test_res']
            res[i-1][j,1] = acc['test_res']

In [9]:
np.round(res.mean(axis=0) * 100, decimals=2)

array([[18.3 , 25.11],
       [ 7.98, 11.34],
       [35.96, 48.03],
       [13.09, 20.83],
       [22.38, 32.02],
       [11.44, 14.74],
       [ 0.1 ,  0.39]])

In [10]:
np.round(res.std(axis=0) * 100, decimals=2)

array([[1.07, 2.47],
       [1.12, 1.65],
       [1.55, 1.84],
       [2.25, 1.5 ],
       [1.48, 1.24],
       [1.79, 3.15],
       [0.12, 0.19]])

In [17]:
import skopt

In [18]:
n_repeat = 5
dim = np.zeros((n_repeat,len(emb_types)))
for i in range(1,n_repeat+1):
    for j,emb_type in enumerate(emb_types):
        res_name =  '_'.join(['res-hyp',num_src, exp_type, emb_type])
        hyp = skopt.load(join('data',str(i),res_name+'.pkl'))
        dim[i-1][j] = hyp.x[1]

In [20]:
np.ceil(dim.mean(axis=0))

array([154., 152., 186., 166., 166., 153., 103.])

In [23]:
np.ceil(dim.mean())

154.0