In [2]:
import numpy as np
from os.path import join
exp_type = 'sc-k'
num_src = 'nums1-3'

emb_types = ['word2vec-wiki', 'word2vec-giga', 'glove-wiki', 'glove-giga', 'fasttext-wiki', 'fasttext-giga','random']

In [10]:
n_repeat = 5
res = np.zeros((n_repeat,len(emb_types),2))
for i in range(1,n_repeat+1):
    for j,emb_type in enumerate(emb_types):
        res_name =  '_'.join(['res-acc',num_src, exp_type, emb_type])
        res[i-1][j,:] = np.load(join('data',str(i),res_name+'.npy'))

In [14]:
np.round(res.mean(axis=0) * 100, decimals=2) 

array([[18.54, 26.47],
       [ 7.35, 13.14],
       [37.62, 48.03],
       [12.94, 20.15],
       [23.41, 35.52],
       [11.58, 17.08],
       [ 1.17,  1.61]])

In [15]:
np.round(res.std(axis=0) * 100, decimals=2) 

array([[1.17, 1.76],
       [0.68, 1.38],
       [2.49, 1.27],
       [1.48, 1.46],
       [1.37, 2.43],
       [0.57, 1.24],
       [0.28, 0.5 ]])

In [17]:
import skopt

In [18]:
n_repeat = 5
dim = np.zeros((n_repeat,len(emb_types)))
for i in range(1,n_repeat+1):
    for j,emb_type in enumerate(emb_types):
        res_name =  '_'.join(['res-hyp',num_src, exp_type, emb_type])
        hyp = skopt.load(join('data',str(i),res_name+'.pkl'))
        dim[i-1][j] = hyp.x[1]

In [20]:
np.ceil(dim.mean(axis=0))

array([154., 152., 186., 166., 166., 153., 103.])

In [23]:
np.ceil(dim.mean())

154.0